locateJP = {
    "LP":    ("Link's Pocket", "手元"),
    "KF":    ("Kokiri Forest", "コキリの森"),
    "LW":    ("the Lost Woods", "迷いの森"),
    "SFM":   ("Sacred Forest Meadow", "森の聖域"),
    "HF":    ("Hyrule Field", "ハイラル平原"),
    "LH":    ("Lake Hylia", "ハイリア湖畔"),
    "GV":    ("Gerudo Valley", "ゲルドの谷"),
    "GF":    ("Gerudo Fortress", "ゲルドの砦"),
    "HW":    ("Haunted Wasteland", "幻影の砂漠"),
    "DC":    ("Desert Colossus", "巨大邪神像"),
    "TM":    ("the Market", "城下町"),
    "TOT":   ("Temple of Time", "時の神殿"),
    "HC":    ("Hyrule Castle", "ハイラル城"),
    "OGC":   ("outside Ganon's Castle", "ガノン城外"),
    "KV":    ("Kakariko Village", "カカリコ村"),
    "TG":    ("the Graveyard", "墓地"),
    "DMT":   ("Death Mountain Trail", "登山道"),
    "GC":    ("Goron City", "ゴロンシティ"),
    "DMC":   ("Death Mountain Crater", "火口"),
    "ZR":    ("Zora's River", "ゾーラ川"),
    "ZD":    ("Zora's Domain", "ゾーラの里"),
    "ZF":    ("Zora's Fountain", "ゾーラの泉"),
    "LLR":   ("Lon Lon Ranch", "牧場"),
    "DT":    ("Deku Tree", "デクの樹"),
    "DGC":   ("Dodongo\'s Cavern", "ドドンゴ"),
    "JJB":   ("Jabu Jabu\'s Belly", "ジャブジャブ"),
    "FOT":   ("Forest Temple", "森の神殿"),
    "FIT":   ("Fire Temple", "炎の神殿"),
    "WT":    ("Water Temple", "水の神殿"),
    "SHT":   ("Shadow Temple", "闇の神殿"),
    "SPT":   ("Spirit Temple", "魂の神殿"),
    "IC":    ("Ice Cavern", "氷の洞窟"),
    "BOTW":  ("Bottom of the Well", "井戸の下"),
    "GTG":   ("Gerudo Training Ground", "修練場"),
    "GAC":   ("Ganon\'s Castle", "ガノン城"),
}
LocationJP = {**locateJP}
