locateJP = {
    "Links Pocket":    ("Link's Pocket", "手元", "Low"),
    "Song from":       ("yveijugc", "誰かの歌", "High"),
    "Sheik":       ("kohsvouc", "シーク", "High"),
    "KF":    ("Kokiri Forest", "コキリの森", "Low"),
    "LW":    ("the Lost Woods", "迷いの森", "Low"),
    "SFM":   ("Sacred Forest Meadow", "森の聖域", "Low"),
    "HF":    ("Hyrule Field", "ハイラル平原", "Low"),
    "LH":    ("Lake Hylia", "ハイリア湖畔", "Low"),
    "GV":    ("Gerudo Valley", "ゲルドの谷", "Low"),
    "GF":    ("Gerudo Fortress", "ゲルドの砦", "Low"),
    "Wasteland":    ("Haunted Wasteland", "幻影の砂漠", "Middle"),
    "Colossus":    ("Desert Colossus", "巨大邪神像", "Low"),
    "Market":    ("the Market", "城下町", "Low"),
    "ToT":   ("Temple of Time", "時の神殿", "Middle"),
    "HC":    ("Hyrule Castle", "ハイラル城", "Low"),
    "OGC":   ("outside Ganon's Castle", "ガノン城外", "Middle"),
    "Great Fairy": ("oubevoi", "大妖精の泉", "High"),
    "Kak":    ("Kakariko Village", "カカリコ村", "Low"),
    "Graveyard":    ("the Graveyard", "墓地", "Middle"),
    "DMT":   ("Death Mountain Trail", "登山道", "Low"),
    "GC":    ("Goron City", "ゴロンシティ", "Low"),
    "DMC":   ("Death Mountain Crater", "火口", "Low"),
    "ZR":    ("Zora's River", "ゾーラ川", "Low"),
    "ZD":    ("Zora's Domain", "ゾーラの里", "Low"),
    "ZF":    ("Zora's Fountain", "ゾーラの泉", "Low"),
    "LLR":   ("Lon Lon Ranch", "牧場", "Low"),
    "Hideout": ("uyfveiygcu", "アジト", "Middle"),
    "Deku Tree":    ("Deku Tree", "デクの樹", "Middle"),
    "Deku Theater": ("Deku Theater", "お面評論会", "High"),
    "Dodongos Cavern":   ("Dodongo\'s Cavern", "ドドンゴ", "High"),
    "Jabu Jabus Belly":   ("Jabu Jabu\'s Belly", "ジャブジャブ", "High"),
    "Forest Temple":   ("Forest Temple", "森の神殿", "High"),
    "Fire Temple":   ("Fire Temple", "炎の神殿", "High"),
    "Water Temple":    ("Water Temple", "水の神殿", "High"),
    "Shadow Temple":   ("Shadow Temple", "闇の神殿", "High"),
    "Spirit Temple":   ("Spirit Temple", "魂の神殿", "High"),
    "Ice Cavern":    ("Ice Cavern", "氷の洞窟", "High"),
    "Bottom of the Well":  ("Bottom of the Well", "井戸の下", "High"),
    "Gerudo Training Ground":   ("Gerudo Training Ground", "修練場", "High"),
    "Ganons Castle":   ("Ganon\'s Castle", "ガノン城", "Low"),
    "Ganons Tower":    ("liyviuv;", "ガノン城", "Middle"),
}
LocationJP = {**locateJP}
itemJP = {
    'Triforce Piece':                                           (["勝利の欠片", "チーズ", "金の欠片"], "トライフォース", "item"),
    'Magic Meter':                                              (["緑の神秘","緑の線"], "魔力増加", 'item'),
    'Double Defense':                                           (["白いハート", "ダメージ減少"], "防御二倍", 'item'),
    'Slingshot':                                                (["タネ飛ばし", "ゴム", "カタパルト"], "パチンコ", 'item'),
    'Boomerang':                                                (["バナナ", "スタン棒"], "ブーメラン", 'item'),
    'Bow':                                                      (["矢飛ばし", "ダーツ飛ばし"], "弓", 'item'),
    'Bomb Bag':                                                 (["爆発物の袋", "体飛ばし"], "ボム袋", 'item'),
    'Progressive Hookshot':                                     (["ダンペイの記念品", "取り付く線"], "フックショット", 'item'),
    'Progressive Strength Upgrade':                             (["力のグローブ", "力持ち"], "うでわ", 'item'),
    'Progressive Scale':                                        (["水深増加", "ゾーラの欠片"], "ウロコ", 'item'),
    'Megaton Hammer':                                           (["ドラゴンスマッシャー", "鉄のマレット"], "メガトンハンマー", 'item'),
    'Iron Boots':                                               (["重いクツ", "耐風クツ"], "ヘビーブーツ", 'item'),
    'Hover Boots':                                              (["滑らかなクツ", "聖なるスリッパ", "滑り歩き"], "ホバーブーツ", 'item'),
    'Kokiri Sword':                                             (["バターナイフ", "スターター剣", "飛び出しナイフ"], "コキリの剣", 'item'),
    'Giants Knife':                                             (["脆い刃", "壊れる包丁"], "巨人のナイフ", 'item'),
    'Biggoron Sword':                                           (["最大の刀", "壊れない包丁"], "ダイゴロン刀", 'item'),
    'Master Sword':                                             (["聖なる包丁"], "マスターソード", 'item'),
    'Deku Shield':                                              (["木の盾", "燃える盾"], "デクの盾", 'item'),
    'Hylian Shield':                                            (["鉄の盾", "ライクライクの鉄分"], "ハイリアの盾", 'item'),
    'Mirror Shield':                                            (["跳ね返す城壁", "メデューサの弱点", "顔の映る表面"], "ミラーシールド", 'item'),
    'Farores Wind':                                             (["テレポート", "場所移し", "緑の玉", "緑の風"], "フロルの風", 'item'),
    'Nayrus Love':                                              (["難攻不落のオーラ", "青い守り", "青い玉"], "ネールの愛", 'item'),
    'Dins Fire':                                                (["インフェルノ", "熱波", "赤い玉"], "ディンの炎", 'item'),
    'Fire Arrows':                                              (["燃える矢", "マグマミサイル"], "炎の矢", 'item'),
    'Ice Arrows':                                               (["冷えた矢", "凍る矢", "使えない矢"], "氷の矢", 'item'),
    'Light Arrows':                                             (["光", "飛ばせる輝き", "聖なる矢"], "光の矢", 'item'),
    'Lens of Truth':                                            (["うそ発見器", "霊の追跡機", "真実を見る", "探偵のツール"], "まことのメガネ", 'item'),
    'Ocarina':                                                  (["笛", "曲鳴らし"], "オカリナ", 'item'),
    'Goron Tunic':                                              (["ルビーの服", "耐火服"], "ゴロンの服", 'item'),
    'Zora Tunic':                                               (["サファイアの服", "スキューバ", "水着"], "ゾーラの服", 'item'),
    'Epona':                                                    (["馬", "四足の友達"], "エポナ", 'item'),
    'Zeldas Lullaby':                                           (["王家の眠り歌", "フォースの歌"], "ゼルダの子守歌", 'item'),
    'Eponas Song':                                              (["馬術の歌", "マロンの歌", "牧場の歌"], "エポナの歌", 'item'),
    'Sarias Song':                                              (["ゴロンの踊る歌", "サリアの電話番号"], "サリアの歌", 'item'),
    'Suns Song':                                                (["晴天の歌", "リーデッドの天敵", "ギブドの天敵"], "太陽の歌", 'item'),
    'Song of Time':                                             (["７年を語る歌", "時をかける歌"], "時の歌", 'item'),
    'Song of Storms':                                           (["雨踊り", "雷雨の歌", "風車を加速する歌"], "嵐の歌", 'item'),
    'Minuet of Forest':                                         (["高木の歌", "樹木の歌", "緑に輝く歌"], "森のメヌエット", 'item'),
    'Bolero of Fire':                                           (["溶岩の歌", "赤に輝く歌", "火山の歌"], "炎のボレロ", 'item'),
    'Serenade of Water':                                        (["湿溝の歌", "青に輝く歌", "川の歌"], "水のセレナーデ", 'item'),
    'Requiem of Spirit':                                        (["砂の宮殿の歌", "橙に輝く歌", "砂漠の歌"], "魂のレクイエム", 'item'),
    'Nocturne of Shadow':                                       (["魂の歌", "墓場の歌", "呪われた歌", "紫に輝く歌"], "闇のノクターン", 'item'),
    'Prelude of Light':                                         (["平和の光の歌", "黄色に輝く歌", "神殿の歌"], "光のプレリュード", 'item'),
    'Bottle':                                                   (["グラス", "万能瓶", "空気瓶"], "空き瓶", 'item'),
    'Rutos Letter':                                             (["助け", "ムニッへの手紙", "ＳＯＳ", "サカナの手紙"], "ルトの手紙", 'item'),
    'Bottle with Milk':                                         (["牛の恵み", "白い瓶", "赤子の食べ物"], "牛乳", 'item'),
    'Bottle with Red Potion':                                   (["活力の瓶", "赤い瓶"], "赤いクスリ", 'item'),
    'Bottle with Green Potion':                                 (["魔法の瓶", "緑の瓶"], "緑のクスリ", 'item'),
    'Bottle with Blue Potion':                                  (["病の特高瓶", "青い瓶"], "青いクスリ", 'item'),
    'Bottle with Fairy':                                        (["囚われた妖精", "１ＵＰ", "ナビィの親戚"], "妖精", 'item'),
    'Bottle with Fish':                                         (["水槽", "ジャブジャブの餌"], "サカナ", 'item'),
    'Bottle with Blue Fire':                                    (["青い引火瓶", "解氷瓶"], "青い炎", 'item'),
    'Bottle with Bugs':                                         (["昆虫", "トークン探知機"], "虫", 'item'),
    'Bottle with Poe':                                          (["幽霊", "顔入り瓶"], "ポウ", 'item'),
    'Bottle with Big Poe':                                      (["大いなる幽霊", "大きな幽霊"], "ビッグポウ", 'item'),
    'Stone of Agony':                                           (["震える石", "振動パック（Ｒ）"], "もだえ石", 'item'),
    'Gerudo Membership Card':                                   (["ゲルドクラブ", "部族証"], "ゲルド会員証", 'item'),
    'Progressive Wallet':                                       (["金銭増加", "宝石入れ", "小さな銀行"], "サイフ", 'item'),
    'Deku Stick Capacity':                                      (["棒ストック", "可燃ストック"], "棒増加", 'item'),
    'Deku Nut Capacity':                                        (["目晦まし増加"], "種増加", 'item'),
    'Heart Container':                                          (["愛の器", "本命チョコ", "ボスの心"], "ハートの器", 'item'),
    'Piece of Heart':                                           (["小さな愛", "壊れた心"], "ハートの欠片", 'item'),
    'Piece of Heart (Treasure Chest Game)':                     ("義理チョコ", "ハートの欠片", 'item'),
    'Recovery Heart':                                           (["回復の愛", "友チョコ", "絆創膏"], "回復のハート", 'item'),
    'Rupee (Treasure Chest Game)':                              ("緑のゴミ", '１ルピー', 'item'),
    'Deku Stick (1)':                                           ("壊れる枝", 'デクの棒', 'item'),
    'Rupee (1)':                                                (["１銭", "緑の宝石"], "１ルピー", 'item'),
    'Rupees (5)':                                               (["いつもの", "青いゴミ"], "５ルピー", 'item'),
    'Rupees (20)':                                              (["程良いルピー", "赤い宝石"], "２０ルピー", 'item'),
    'Rupees (50)':                                              (["紫の宝石", "財貨"], "５０ルピー", 'item'),
    'Rupees (200)':                                             (["ジャックポット", "黄色い宝石", "大きいルピー", "富"], "２００ルピー", 'item'),
    'Weird Egg':                                                (["コッコのジレンマ"], "不思議なタマゴ", 'item'),
    'Zeldas Letter':                                            (["王家のサイン", "王家の手紙", "姫の手紙"], "ゼルダの手紙", 'item'),
    'Pocket Egg':                                               (["コッコの殻", "ほぼコッコ", "若いコッコ"], "ポケットタマゴ", 'item'),
    'Pocket Cucco':                                             (["目覚まし時計"], "てのりコッコ", 'item'),
    'Cojiro':                                                   (["青いコッコ"], "コジロー", 'item'),
    'Odd Mushroom':                                             (["粉の素材"], "あやしいキノコ", 'item'),
    'Odd Potion':                                               (["おばばのクスリ"], "あやしいクスリ", 'item'),
    'Poachers Saw':                                             (["木殺し"], "ノコギリ", 'item'),
    'Broken Sword':                                             (["壊れた刃"], "折れた刀", 'item'),
    'Prescription':                                             (["クスリの予約表", "医者の書留"], "処方せん", 'item'),
    'Eyeball Frog':                                             (["大人のオタマジャクシ"], "カエル", 'item'),
    'Eyedrops':                                                 (["視力回復"], "目薬", 'item'),
    'Claim Check':                                              (["３日待ち"], "ひきかえ券", 'item'),
    'Map':                                                      (["ダンジョン地図", "見取り図"], "地図", 'item'),
    'Map (Deku Tree)':                                          (["木の地図", "木の見取り図"], "デクの樹の地図", 'item'),
    'Map (Dodongos Cavern)':                                    (["洞窟の地図", "洞窟の案内図"], "ドドンゴの地図", 'item'),
    'Map (Jabu Jabus Belly)':                                   (["水神の地図", "水神の見取り図"], "ジャブジャブの地図", 'item'),
    'Map (Forest Temple)':                                      (["深き森の地図", "深き森の案内図"], "森の神殿の地図", 'item'),
    'Map (Fire Temple)':                                        (["高き山の地図", "高き山の案内図"], "炎の神殿の地図", 'item'),
    'Map (Water Temple)':                                       (["広き湖の地図", "広き湖の見取り図"], "水の神殿の地図", 'item'),
    'Map (Shadow Temple)':                                      (["屍の館の地図", "館の見取り図"], "闇の神殿の地図", 'item'),
    'Map (Spirit Temple)':                                      (["砂の女神の地図", "女神の見取り図"], "魂の神殿の地図", 'item'),
    'Map (Bottom of the Well)':                                 (["井戸の地図", "井戸の見取り図"], "井戸の下の地図", 'item'),
    'Map (Ice Cavern)':                                         (["凍る地図", "凍る案内図"], "氷の洞窟の地図", 'item'),
    'Compass':                                                  (["宝探知機", "羅針盤"], "コンパス", 'item'),
    'Compass (Deku Tree)':                                      (["木の探知機", "木の羅針盤"], "デクの樹のコンパス", 'item'),
    'Compass (Dodongos Cavern)':                                (["洞窟の探知機", "洞窟の羅針盤"], "ドドンゴのコンパス", 'item'),
    'Compass (Jabu Jabus Belly)':                               (["水神の探知機", "水神の羅針盤"], "ジャブジャブのコンパス", 'item'),
    'Compass (Forest Temple)':                                  (["深き森の探知機", "深き森の羅針盤"], "森のコンパス", 'item'),
    'Compass (Fire Temple)':                                    (["高き山の探知機", "高き山の羅針盤"], "炎のコンパス", 'item'),
    'Compass (Water Temple)':                                   (["広き湖の探知機", "広き湖の羅針盤"], "水のコンパス", 'item'),
    'Compass (Shadow Temple)':                                  (["屍の館の探知機", "屍の館の羅針盤"], "闇のコンパス", 'item'),
    'Compass (Spirit Temple)':                                  (["女神の探知機", "女神の羅針盤"], "魂のコンパス", 'item'),
    'Compass (Bottom of the Well)':                             (["井戸の探知機", "井戸の羅針盤"], "井戸下のコンパス", 'item'),
    'Compass (Ice Cavern)':                                     (["凍る探知機", "凍る羅針盤"], "氷のコンパス", 'item'),
    'BossKey':                                                  (["解除の達人", "大きなカギ"], "ボスキー", 'item'),
    'GanonBossKey':                                             (["解除の達人", "大きなカギ"], "ボスキー", 'item'),
    'SmallKey':                                                 (["解除のツール", "扉開け", "ロックピック"], "小さなカギ", 'item'),
    'HideoutSmallKey':                                          (["釈放カード"], "牢屋のカギ", 'item'),
    'Boss Key (Forest Temple)':                                 (["解除の達人", "大きなカギ"], "森のボスキー", 'item'),
    'Boss Key (Fire Temple)':                                   (["解除の達人", "大きなカギ"], "炎のボスキー", 'item'),
    'Boss Key (Water Temple)':                                  (["解除の達人", "大きなカギ"], "水のボスキー", 'item'),
    'Boss Key (Shadow Temple)':                                 (["解除の達人", "大きなカギ"], "闇のボスキー", 'item'),
    'Boss Key (Spirit Temple)':                                 (["解除の達人", "大きなカギ"], "魂のボスキー", 'item'),
    'Boss Key (Ganons Castle)':                                 (["解除の達人", "大きなカギ"], "ガノンボスキー", 'item'),
    'Small Key (Forest Temple)':                                (["解除のツール", "扉開け", "ロックピック"], "森のカギ", 'item'),
    'Small Key (Fire Temple)':                                  (["解除のツール", "扉開け", "ロックピック"], "炎のカギ", 'item'),
    'Small Key (Water Temple)':                                 (["解除のツール", "扉開け", "ロックピック"], "水のカギ", 'item'),
    'Small Key (Shadow Temple)':                                (["解除のツール", "扉開け", "ロックピック"], "闇のカギ", 'item'),
    'Small Key (Spirit Temple)':                                (["解除のツール", "扉開け", "ロックピック"], "魂のカギ", 'item'),
    'Small Key (Bottom of the Well)':                           (["解除のツール", "扉開け", "ロックピック"], "井戸下のカギ", 'item'),
    'Small Key (Gerudo Training Ground)':                       (["解除のツール", "扉開け", "ロックピック"], "修練場のカギ", 'item'),
    'Small Key (Ganons Castle)':                                (["解除のツール", "扉開け", "ロックピック"], "ガノンのカギ", 'item'),
    'Small Key (Thieves Hideout)':                              (["釈放カード"], "牢屋のカギ", 'item'),
    'KeyError':                                                 (["けつばん", "なぞのもの"], "エラー", 'item'),
    'Arrows (5)':                                               (["少しの矢"], "矢（５本）", 'item'),
    'Arrows (10)':                                              (["いくつかの矢"], "矢（１０本）", 'item'),
    'Arrows (30)':                                              (["多くの矢"], "矢（３０本）", 'item'),
    'Bombs (5)':                                                (["少しのバクダン"], "バクダン（５コ）", 'item'),
    'Bombs (10)':                                               (["いくつかのバクダン"], "バクダン（１０コ）", 'item'),
    'Bombs (20)':                                               (["多くのバクダン"], "バクダン（２０コ）", 'item'),
    'Magic Bean':                                               (["不思議なマメ"], "魔法のマメ", 'item'),
    'Magic Bean Pack':                                          (["不思議なマメ"], "魔法のマメ", 'item'),
    'Bombchus':                                                 (["ネズミ", "壁バクダン", "走るバクダン"], "ボムチュウ", 'item'),
    'Bombchus (5)':                                             (["少しのネズミ", "少しの動バクダン", "少しの走バクダン"], "ボムチュウ（５コ）", 'item'),
    'Bombchus (10)':                                            (["いくつかのネズミ", "いくつかの動バクダン", "いくつかの走バクダン"], "ボムチュウ（１０コ）", 'item'),
    'Bombchus (20)':                                            (["多くのネズミ", "多くの動バクダン", "多くの走バクダン"], "ボムチュウ（２０コ）", 'item'),
    'Deku Nuts (5)':                                            (["いくつかの実", "いくつかの目くらまし"], "デクの実（５コ）", 'item'),
    'Deku Nuts (10)':                                           (["多くの実", "多くの目くらまし"], "デクの実（１０コ）", 'item'),
    'Deku Seeds (30)':                                          (["カタパルトの玉", "多くの種"], "デクの種（３０コ）", 'item'),
    'Gold Skulltula Token':                                     (["破壊の証拠", "クモの金", "クモの残し物", "呪いの欠片"], "トークン", 'item'),
}
ItemTrJP = {**itemJP}          