#![allow(unused_qualifications)] // for generated code

use {
    std::collections::HashMap,
    collect_mac::collect,
    indexmap::IndexMap,
    pyo3::{
        IntoPyObjectExt as _,
        prelude::*,
    },
};

const ADVANCEMENT: Option<bool> = Some(true);
const PRIORITY: Option<bool> = Some(false);
const NORMAL: Option<bool> = None;

fn get_item_id() -> HashMap<&'static str, u16> {
    collect![
        "GI_NONE" => 0x0000,
        "GI_BOMBS_5" => 0x0001,
        "GI_DEKU_NUTS_5" => 0x0002,
        "GI_BOMBCHUS_10" => 0x0003,
        "GI_BOW" => 0x0004,
        "GI_SLINGSHOT" => 0x0005,
        "GI_BOOMERANG" => 0x0006,
        "GI_DEKU_STICKS_1" => 0x0007,
        "GI_HOOKSHOT" => 0x0008,
        "GI_LONGSHOT" => 0x0009,
        "GI_LENS_OF_TRUTH" => 0x000A,
        "GI_ZELDAS_LETTER" => 0x000B,
        "GI_OCARINA_OF_TIME" => 0x000C,
        "GI_HAMMER" => 0x000D,
        "GI_COJIRO" => 0x000E,
        "GI_BOTTLE_EMPTY" => 0x000F,
        "GI_BOTTLE_POTION_RED" => 0x0010,
        "GI_BOTTLE_POTION_GREEN" => 0x0011,
        "GI_BOTTLE_POTION_BLUE" => 0x0012,
        "GI_BOTTLE_FAIRY" => 0x0013,
        "GI_BOTTLE_MILK_FULL" => 0x0014,
        "GI_BOTTLE_RUTOS_LETTER" => 0x0015,
        "GI_MAGIC_BEAN" => 0x0016,
        "GI_MASK_SKULL" => 0x0017,
        "GI_MASK_SPOOKY" => 0x0018,
        "GI_CHICKEN" => 0x0019,
        "GI_MASK_KEATON" => 0x001A,
        "GI_MASK_BUNNY_HOOD" => 0x001B,
        "GI_MASK_TRUTH" => 0x001C,
        "GI_POCKET_EGG" => 0x001D,
        "GI_POCKET_CUCCO" => 0x001E,
        "GI_ODD_MUSHROOM" => 0x001F,
        "GI_ODD_POTION" => 0x0020,
        "GI_POACHERS_SAW" => 0x0021,
        "GI_BROKEN_GORONS_SWORD" => 0x0022,
        "GI_PRESCRIPTION" => 0x0023,
        "GI_EYEBALL_FROG" => 0x0024,
        "GI_EYE_DROPS" => 0x0025,
        "GI_CLAIM_CHECK" => 0x0026,
        "GI_SWORD_KOKIRI" => 0x0027,
        "GI_SWORD_KNIFE" => 0x0028,
        "GI_SHIELD_DEKU" => 0x0029,
        "GI_SHIELD_HYLIAN" => 0x002A,
        "GI_SHIELD_MIRROR" => 0x002B,
        "GI_TUNIC_GORON" => 0x002C,
        "GI_TUNIC_ZORA" => 0x002D,
        "GI_BOOTS_IRON" => 0x002E,
        "GI_BOOTS_HOVER" => 0x002F,
        "GI_QUIVER_40" => 0x0030,
        "GI_QUIVER_50" => 0x0031,
        "GI_BOMB_BAG_20" => 0x0032,
        "GI_BOMB_BAG_30" => 0x0033,
        "GI_BOMB_BAG_40" => 0x0034,
        "GI_SILVER_GAUNTLETS" => 0x0035,
        "GI_GOLD_GAUNTLETS" => 0x0036,
        "GI_SCALE_SILVER" => 0x0037,
        "GI_SCALE_GOLDEN" => 0x0038,
        "GI_STONE_OF_AGONY" => 0x0039,
        "GI_GERUDOS_CARD" => 0x003A,
        "GI_OCARINA_FAIRY" => 0x003B,
        "GI_DEKU_SEEDS_5" => 0x003C,
        "GI_HEART_CONTAINER" => 0x003D,
        "GI_HEART_PIECE" => 0x003E,
        "GI_BOSS_KEY" => 0x003F,
        "GI_COMPASS" => 0x0040,
        "GI_DUNGEON_MAP" => 0x0041,
        "GI_SMALL_KEY" => 0x0042,
        "GI_MAGIC_JAR_SMALL" => 0x0043,
        "GI_MAGIC_JAR_LARGE" => 0x0044,
        "GI_WALLET_ADULT" => 0x0045,
        "GI_WALLET_GIANT" => 0x0046,
        "GI_WEIRD_EGG" => 0x0047,
        "GI_RECOVERY_HEART" => 0x0048,
        "GI_ARROWS_5" => 0x0049,
        "GI_ARROWS_10" => 0x004A,
        "GI_ARROWS_30" => 0x004B,
        "GI_RUPEE_GREEN" => 0x004C,
        "GI_RUPEE_BLUE" => 0x004D,
        "GI_RUPEE_RED" => 0x004E,
        "GI_HEART_CONTAINER_2" => 0x004F,
        "GI_MILK" => 0x0050,
        "GI_MASK_GORON" => 0x0051,
        "GI_MASK_ZORA" => 0x0052,
        "GI_MASK_GERUDO" => 0x0053,
        "GI_GORONS_BRACELET" => 0x0054,
        "GI_RUPEE_PURPLE" => 0x0055,
        "GI_RUPEE_GOLD" => 0x0056,
        "GI_SWORD_BIGGORON" => 0x0057,
        "GI_ARROW_FIRE" => 0x0058,
        "GI_ARROW_ICE" => 0x0059,
        "GI_ARROW_LIGHT" => 0x005A,
        "GI_SKULL_TOKEN" => 0x005B,
        "GI_DINS_FIRE" => 0x005C,
        "GI_FARORES_WIND" => 0x005D,
        "GI_NAYRUS_LOVE" => 0x005E,
        "GI_BULLET_BAG_30" => 0x005F,
        "GI_BULLET_BAG_40" => 0x0060,
        "GI_DEKU_STICKS_5" => 0x0061,
        "GI_DEKU_STICKS_10" => 0x0062,
        "GI_DEKU_NUTS_5_2" => 0x0063,
        "GI_DEKU_NUTS_10" => 0x0064,
        "GI_BOMBS_1" => 0x0065,
        "GI_BOMBS_10" => 0x0066,
        "GI_BOMBS_20" => 0x0067,
        "GI_BOMBS_30" => 0x0068,
        "GI_DEKU_SEEDS_30" => 0x0069,
        "GI_BOMBCHUS_5" => 0x006A,
        "GI_BOMBCHUS_20" => 0x006B,
        "GI_BOTTLE_FISH" => 0x006C,
        "GI_BOTTLE_BUGS" => 0x006D,
        "GI_BOTTLE_BLUE_FIRE" => 0x006E,
        "GI_BOTTLE_POE" => 0x006F,
        "GI_BOTTLE_BIG_POE" => 0x0070,
        "GI_DOOR_KEY" => 0x0071,
        "GI_RUPEE_GREEN_LOSE" => 0x0072,
        "GI_RUPEE_BLUE_LOSE" => 0x0073,
        "GI_RUPEE_RED_LOSE" => 0x0074,
        "GI_RUPEE_PURPLE_LOSE" => 0x0075,
        "GI_HEART_PIECE_WIN" => 0x0076,
        "GI_DEKU_STICK_UPGRADE_20" => 0x0077,
        "GI_DEKU_STICK_UPGRADE_30" => 0x0078,
        "GI_DEKU_NUT_UPGRADE_30" => 0x0079,
        "GI_DEKU_NUT_UPGRADE_40" => 0x007A,
        "GI_BULLET_BAG_50" => 0x007B,
        "GI_ICE_TRAP" => 0x007C,

        "GI_CAPPED_PIECE_OF_HEART" => 0x007D,
        "GI_CAPPED_HEART_CONTAINER" => 0x007E,

        "GI_CAPPED_PIECE_OF_HEART_CHESTGAME" => 0x007F,

        "GI_PROGRESSIVE_HOOKSHOT" => 0x0080,
        "GI_PROGRESSIVE_STRENGTH" => 0x0081,
        "GI_PROGRESSIVE_BOMB_BAG" => 0x0082,
        "GI_PROGRESSIVE_BOW" => 0x0083,
        "GI_PROGRESSIVE_SLINGSHOT" => 0x0084,
        "GI_PROGRESSIVE_WALLET" => 0x0085,
        "GI_PROGRESSIVE_SCALE" => 0x0086,
        "GI_PROGRESSIVE_NUT_CAPACITY" => 0x0087,
        "GI_PROGRESSIVE_STICK_CAPACITY" => 0x0088,
        "GI_PROGRESSIVE_BOMBCHUS" => 0x0089,
        "GI_PROGRESSIVE_MAGIC_METER" => 0x008A,
        "GI_PROGRESSIVE_OCARINA" => 0x008B,

        "GI_BOTTLE_WITH_RED_POTION" => 0x008C,
        "GI_BOTTLE_WITH_GREEN_POTION" => 0x008D,
        "GI_BOTTLE_WITH_BLUE_POTION" => 0x008E,
        "GI_BOTTLE_WITH_FAIRY" => 0x008F,
        "GI_BOTTLE_WITH_FISH" => 0x0090,
        "GI_BOTTLE_WITH_BLUE_FIRE" => 0x0091,
        "GI_BOTTLE_WITH_BUGS" => 0x0092,
        "GI_BOTTLE_WITH_BIG_POE" => 0x0093,
        "GI_BOTTLE_WITH_POE" => 0x0094,

        "GI_BOSS_KEY_FOREST_TEMPLE" => 0x0095,
        "GI_BOSS_KEY_FIRE_TEMPLE" => 0x0096,
        "GI_BOSS_KEY_WATER_TEMPLE" => 0x0097,
        "GI_BOSS_KEY_SPIRIT_TEMPLE" => 0x0098,
        "GI_BOSS_KEY_SHADOW_TEMPLE" => 0x0099,
        "GI_BOSS_KEY_GANONS_CASTLE" => 0x009A,

        "GI_COMPASS_DEKU_TREE" => 0x009B,
        "GI_COMPASS_DODONGOS_CAVERN" => 0x009C,
        "GI_COMPASS_JABU_JABU" => 0x009D,
        "GI_COMPASS_FOREST_TEMPLE" => 0x009E,
        "GI_COMPASS_FIRE_TEMPLE" => 0x009F,
        "GI_COMPASS_WATER_TEMPLE" => 0x00A0,
        "GI_COMPASS_SPIRIT_TEMPLE" => 0x00A1,
        "GI_COMPASS_SHADOW_TEMPLE" => 0x00A2,
        "GI_COMPASS_BOTTOM_OF_THE_WELL" => 0x00A3,
        "GI_COMPASS_ICE_CAVERN" => 0x00A4,

        "GI_MAP_DEKU_TREE" => 0x00A5,
        "GI_MAP_DODONGOS_CAVERN" => 0x00A6,
        "GI_MAP_JABU_JABU" => 0x00A7,
        "GI_MAP_FOREST_TEMPLE" => 0x00A8,
        "GI_MAP_FIRE_TEMPLE" => 0x00A9,
        "GI_MAP_WATER_TEMPLE" => 0x00AA,
        "GI_MAP_SPIRIT_TEMPLE" => 0x00AB,
        "GI_MAP_SHADOW_TEMPLE" => 0x00AC,
        "GI_MAP_BOTTOM_OF_THE_WELL" => 0x00AD,
        "GI_MAP_ICE_CAVERN" => 0x00AE,

        "GI_SMALL_KEY_FOREST_TEMPLE" => 0x00AF,
        "GI_SMALL_KEY_FIRE_TEMPLE" => 0x00B0,
        "GI_SMALL_KEY_WATER_TEMPLE" => 0x00B1,
        "GI_SMALL_KEY_SPIRIT_TEMPLE" => 0x00B2,
        "GI_SMALL_KEY_SHADOW_TEMPLE" => 0x00B3,
        "GI_SMALL_KEY_BOTTOM_OF_THE_WELL" => 0x00B4,
        "GI_SMALL_KEY_GERUDO_TRAINING" => 0x00B5,
        "GI_SMALL_KEY_THIEVES_HIDEOUT" => 0x00B6,
        "GI_SMALL_KEY_GANONS_CASTLE" => 0x00B7,

        "GI_DOUBLE_DEFENSE" => 0x00B8,
        "GI_MAGIC_METER" => 0x00B9,
        "GI_DOUBLE_MAGIC" => 0x00BA,

        "GI_MINUET_OF_FOREST" => 0x00BB,
        "GI_BOLERO_OF_FIRE" => 0x00BC,
        "GI_SERENADE_OF_WATER" => 0x00BD,
        "GI_REQUIEM_OF_SPIRIT" => 0x00BE,
        "GI_NOCTURNE_OF_SHADOW" => 0x00BF,
        "GI_PRELUDE_OF_LIGHT" => 0x00C0,

        "GI_ZELDAS_LULLABY" => 0x00C1,
        "GI_EPONAS_SONG" => 0x00C2,
        "GI_SARIAS_SONG" => 0x00C3,
        "GI_SUNS_SONG" => 0x00C4,
        "GI_SONG_OF_TIME" => 0x00C5,
        "GI_SONG_OF_STORMS" => 0x00C6,

        "GI_TYCOONS_WALLET" => 0x00C7,
        "GI_REDUNDANT_LETTER_BOTTLE" => 0x00C8,
        "GI_MAGIC_BEAN_PACK" => 0x00C9,
        "GI_TRIFORCE_PIECE" => 0x00CA,

        "GI_SMALL_KEY_RING_FOREST_TEMPLE" => 0x00CB,
        "GI_SMALL_KEY_RING_FIRE_TEMPLE" => 0x00CC,
        "GI_SMALL_KEY_RING_WATER_TEMPLE" => 0x00CD,
        "GI_SMALL_KEY_RING_SPIRIT_TEMPLE" => 0x00CE,
        "GI_SMALL_KEY_RING_SHADOW_TEMPLE" => 0x00CF,
        "GI_SMALL_KEY_RING_BOTTOM_OF_THE_WELL" => 0x00D0,
        "GI_SMALL_KEY_RING_GERUDO_TRAINING" => 0x00D1,
        "GI_SMALL_KEY_RING_THIEVES_HIDEOUT" => 0x00D2,
        "GI_SMALL_KEY_RING_GANONS_CASTLE" => 0x00D3,

        "GI_BOMBCHU_BAG_20" => 0x00D4,
        "GI_BOMBCHU_BAG_10" => 0x00D5,
        "GI_BOMBCHU_BAG_5" => 0x00D6,

        "GI_SMALL_KEY_RING_TREASURE_CHEST_GAME" => 0x00D7,

        "GI_SILVER_RUPEE_DODONGOS_CAVERN_STAIRCASE" => 0x00D8,
        "GI_SILVER_RUPEE_ICE_CAVERN_SPINNING_SCYTHE" => 0x00D9,
        "GI_SILVER_RUPEE_ICE_CAVERN_PUSH_BLOCK" => 0x00DA,
        "GI_SILVER_RUPEE_BOTTOM_OF_THE_WELL_BASEMENT" => 0x00DB,
        "GI_SILVER_RUPEE_SHADOW_TEMPLE_SCYTHE_SHORTCUT" => 0x00DC,
        "GI_SILVER_RUPEE_SHADOW_TEMPLE_INVISIBLE_BLADES" => 0x00DD,
        "GI_SILVER_RUPEE_SHADOW_TEMPLE_HUGE_PIT" => 0x00DE,
        "GI_SILVER_RUPEE_SHADOW_TEMPLE_INVISIBLE_SPIKES" => 0x00DF,
        "GI_SILVER_RUPEE_GERUDO_TRAINING_GROUND_SLOPES" => 0x00E0,
        "GI_SILVER_RUPEE_GERUDO_TRAINING_GROUND_LAVA" => 0x00E1,
        "GI_SILVER_RUPEE_GERUDO_TRAINING_GROUND_WATER" => 0x00E2,
        "GI_SILVER_RUPEE_SPIRIT_TEMPLE_CHILD_EARLY_TORCHES" => 0x00E3,
        "GI_SILVER_RUPEE_SPIRIT_TEMPLE_ADULT_BOULDERS" => 0x00E4,
        "GI_SILVER_RUPEE_SPIRIT_TEMPLE_LOBBY_AND_LOWER_ADULT" => 0x00E5,
        "GI_SILVER_RUPEE_SPIRIT_TEMPLE_SUN_BLOCK" => 0x00E6,
        "GI_SILVER_RUPEE_SPIRIT_TEMPLE_ADULT_CLIMB" => 0x00E7,
        "GI_SILVER_RUPEE_GANONS_CASTLE_SPIRIT_TRIAL" => 0x00E8,
        "GI_SILVER_RUPEE_GANONS_CASTLE_LIGHT_TRIAL" => 0x00E9,
        "GI_SILVER_RUPEE_GANONS_CASTLE_FIRE_TRIAL" => 0x00EA,
        "GI_SILVER_RUPEE_GANONS_CASTLE_SHADOW_TRIAL" => 0x00EB,
        "GI_SILVER_RUPEE_GANONS_CASTLE_WATER_TRIAL" => 0x00EC,
        "GI_SILVER_RUPEE_GANONS_CASTLE_FOREST_TRIAL" => 0x00ED,

        "GI_SILVER_RUPEE_POUCH_DODONGOS_CAVERN_STAIRCASE" => 0x00EE,
        "GI_SILVER_RUPEE_POUCH_ICE_CAVERN_SPINNING_SCYTHE" => 0x00EF,
        "GI_SILVER_RUPEE_POUCH_ICE_CAVERN_PUSH_BLOCK" => 0x00F0,
        "GI_SILVER_RUPEE_POUCH_BOTTOM_OF_THE_WELL_BASEMENT" => 0x00F1,
        "GI_SILVER_RUPEE_POUCH_SHADOW_TEMPLE_SCYTHE_SHORTCUT" => 0x00F2,
        "GI_SILVER_RUPEE_POUCH_SHADOW_TEMPLE_INVISIBLE_BLADES" => 0x00F3,
        "GI_SILVER_RUPEE_POUCH_SHADOW_TEMPLE_HUGE_PIT" => 0x00F4,
        "GI_SILVER_RUPEE_POUCH_SHADOW_TEMPLE_INVISIBLE_SPIKES" => 0x00F5,
        "GI_SILVER_RUPEE_POUCH_GERUDO_TRAINING_GROUND_SLOPES" => 0x00F6,
        "GI_SILVER_RUPEE_POUCH_GERUDO_TRAINING_GROUND_LAVA" => 0x00F7,
        "GI_SILVER_RUPEE_POUCH_GERUDO_TRAINING_GROUND_WATER" => 0x00F8,
        "GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_CHILD_EARLY_TORCHES" => 0x00F9,
        "GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_ADULT_BOULDERS" => 0x00FA,
        "GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_LOBBY_AND_LOWER_ADULT" => 0x00FB,
        "GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_SUN_BLOCK" => 0x00FC,
        "GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_ADULT_CLIMB" => 0x00FD,
        "GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_SPIRIT_TRIAL" => 0x00FE,
        "GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_LIGHT_TRIAL" => 0x00FF,
        "GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_FIRE_TRIAL" => 0x0100,
        "GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_SHADOW_TRIAL" => 0x0101,
        "GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_WATER_TRIAL" => 0x0102,
        "GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_FOREST_TRIAL" => 0x0103,

        // Ocarina button models
        "GI_OCARINA_BUTTON_A" => 0x0104,
        "GI_OCARINA_BUTTON_C_UP" => 0x0105,
        "GI_OCARINA_BUTTON_C_DOWN" => 0x0106,
        "GI_OCARINA_BUTTON_C_LEFT" => 0x0107,
        "GI_OCARINA_BUTTON_C_RIGHT" => 0x0108,

        // Custom Key Models
        "GI_BOSS_KEY_MODEL_FOREST_TEMPLE" => 0x0109,
        "GI_BOSS_KEY_MODEL_FIRE_TEMPLE" => 0x010A,
        "GI_BOSS_KEY_MODEL_WATER_TEMPLE" => 0x010B,
        "GI_BOSS_KEY_MODEL_SPIRIT_TEMPLE" => 0x010C,
        "GI_BOSS_KEY_MODEL_SHADOW_TEMPLE" => 0x010D,
        "GI_BOSS_KEY_MODEL_GANONS_CASTLE" => 0x010E,
        "GI_SMALL_KEY_MODEL_FOREST_TEMPLE" => 0x010F,
        "GI_SMALL_KEY_MODEL_FIRE_TEMPLE" => 0x0110,
        "GI_SMALL_KEY_MODEL_WATER_TEMPLE" => 0x0111,
        "GI_SMALL_KEY_MODEL_SPIRIT_TEMPLE" => 0x0112,
        "GI_SMALL_KEY_MODEL_SHADOW_TEMPLE" => 0x0113,
        "GI_SMALL_KEY_MODEL_BOTTOM_OF_THE_WELL" => 0x0114,
        "GI_SMALL_KEY_MODEL_GERUDO_TRAINING" => 0x0115,
        "GI_SMALL_KEY_MODEL_THIEVES_HIDEOUT" => 0x0116,
        "GI_SMALL_KEY_MODEL_GANONS_CASTLE" => 0x0117,
        "GI_SMALL_KEY_MODEL_CHEST_GAME" => 0x0118,

        "GI_FAIRY" => 0x0119,
        "GI_NOTHING" => 0x011A,

        "GI_KOKIRI_EMERALD" => 0x0127,
        "GI_GORON_RUBY" => 0x0128,
        "GI_ZORA_SAPPHIRE" => 0x0129,
        "GI_LIGHT_MEDALLION" => 0x012A,
        "GI_FOREST_MEDALLION" => 0x012B,
        "GI_FIRE_MEDALLION" => 0x012C,
        "GI_WATER_MEDALLION" => 0x012D,
        "GI_SHADOW_MEDALLION" => 0x012E,
        "GI_SPIRIT_MEDALLION" => 0x012F,

        // New items in dev-fenhl which are not in main Dev
        // Some previously used IDs may be skipped, to simplify auto-tracker support

        "GI_EASTER_EGG_PINK" => 0x1000,
        "GI_EASTER_EGG_ORANGE" => 0x1001,
        "GI_EASTER_EGG_GREEN" => 0x1002,
        "GI_EASTER_EGG_BLUE" => 0x1003,
        "GI_TRIFORCE_OF_POWER" => 0x1004,
        "GI_TRIFORCE_OF_WISDOM" => 0x1005,
        "GI_TRIFORCE_OF_COURAGE" => 0x1006,

        "GI_SKULL_TOKEN_NORMAL_TEXT" => 0x1007,
        "GI_SKULL_TOKEN_BIG_CHEST_NORMAL_TEXT" => 0x1008,

        // 0x1009 and 0x100A previously used for Fairy and Nothing respectively
        // 0x100B through 0x1013 previously used for dungeon rewards

        "GI_SMALL_KEY_RING_FOREST_TEMPLE_WITH_BOSS_KEY" => 0x1014,
        "GI_SMALL_KEY_RING_FIRE_TEMPLE_WITH_BOSS_KEY" => 0x1015,
        "GI_SMALL_KEY_RING_WATER_TEMPLE_WITH_BOSS_KEY" => 0x1016,
        "GI_SMALL_KEY_RING_SPIRIT_TEMPLE_WITH_BOSS_KEY" => 0x1017,
        "GI_SMALL_KEY_RING_SHADOW_TEMPLE_WITH_BOSS_KEY" => 0x1018,

        "GI_ARROW_BLUE_FIRE" => 0x1019,

        "GI_SKULL_TOKEN_BIG_CHEST" => 0x101A,
        "GI_HEART_CONTAINER_BIG_CHEST" => 0x101B,
        "GI_HEART_PIECE_BIG_CHEST" => 0x101C,
        "GI_HEART_PIECE_WIN_BIG_CHEST" => 0x101D,
        "GI_SHIELD_DEKU_BIG_CHEST" => 0x101E,
        "GI_SHIELD_HYLIAN_BIG_CHEST" => 0x101F,
        "GI_BOMBCHUS_5_BIG_CHEST" => 0x1020,
        "GI_BOMBCHUS_10_BIG_CHEST" => 0x1021,
        "GI_BOMBCHUS_20_BIG_CHEST" => 0x1022,
        "GI_PROGRESSIVE_NUT_CAPACITY_BIG_CHEST" => 0x1023,
        "GI_PROGRESSIVE_STICK_CAPACITY_BIG_CHEST" => 0x1024,

        "GI_BOMB_BAG_HINT" => 0x1025,
        "GI_BOW_HINT" => 0x1026,
        "GI_HOOKSHOT_HINT" => 0x1027,
        "GI_MAGIC_HINT" => 0x1028,
        "GI_SILVER_GAUNTLETS_HINT" => 0x1029,
        "GI_GORON_BRACELET_HINT" => 0x102A,
        "GI_SILVER_SCALE_HINT" => 0x102B,
        "GI_WALLET_HINT" => 0x102C,
    ]
}

macro_rules! item_table {
    (@get_item_id $py:expr, None) => {
        None
    };
    (@get_item_id $py:expr, $get_item_id:ident) => {
        Some(get_item_id()[stringify!($get_item_id)].into_py_any($py)?)
    };
    (@get_item_id $py:expr, $get_item_id:expr) => {
        Some($get_item_id.into_py_any($py)?)
    };
    ($($name:expr => ($kind:expr, $progressive:expr, $get_item_id:tt, [$($special_key:expr => $special_value:expr),*]),)*) => {
        fn item_table(py: Python<'_>) -> PyResult<IndexMap<&'static str, (&'static str, Option<bool>, Option<Py<PyAny>>, IndexMap<&'static str, Py<PyAny>>)>> {
            Ok(collect![
                $(
                    $name => ($kind, $progressive, item_table!(@get_item_id py, $get_item_id), {
                        #[allow(unused_mut)] let mut special = IndexMap::default();
                        $(
                            special.insert($special_key, $special_value.into_py_any(py)?);
                        )*
                        special
                    }),
                )*
            ])
        }
    };
}

//    Item:                                            (type, Progressive, GetItemID, special),
item_table! {
    "Bombs (5)"                                                => ("Item",                NORMAL,      GI_BOMBS_5,                                                ["junk" => 8_i32, "market_price" => 25_i32]),
    "Deku Nuts (5)"                                            => ("Item",                NORMAL,      GI_DEKU_NUTS_5,                                            ["junk" => 5_i32, "market_price" => 15_i32]),
    "Bombchus (10)"                                            => ("Item",                ADVANCEMENT, GI_BOMBCHUS_10,                                            ["market_price" => 99_i32, "market_price_non_chu_drops_only" => true]),
    "Boomerang"                                                => ("Item",                ADVANCEMENT, GI_BOOMERANG,                                              []),
    "Deku Stick (1)"                                           => ("Item",                NORMAL,      GI_DEKU_STICKS_1,                                          ["junk" => 5_i32, "market_price" => 10_i32]),
    "Lens of Truth"                                            => ("Item",                ADVANCEMENT, GI_LENS_OF_TRUTH,                                          []),
    "Megaton Hammer"                                           => ("Item",                ADVANCEMENT, GI_HAMMER,                                                 []),
    "Cojiro"                                                   => ("Item",                ADVANCEMENT, GI_COJIRO,                                                 ["trade" => true]),
    "Bottle"                                                   => ("Item",                ADVANCEMENT, GI_BOTTLE_EMPTY,                                           ["bottle" => f64::INFINITY]),
    "Blue Potion"                                              => ("Item",                ADVANCEMENT, GI_BOTTLE_POTION_BLUE,                                     []), // distinct from shop item
    "Bottle with Milk"                                         => ("Item",                ADVANCEMENT, GI_BOTTLE_MILK_FULL,                                       ["bottle" => f64::INFINITY]),
    "Rutos Letter"                                             => ("Item",                ADVANCEMENT, GI_BOTTLE_RUTOS_LETTER,                                    []),
    "Deliver Letter"                                           => ("Item",                ADVANCEMENT, None,                                                      ["bottle" => f64::INFINITY]),
    "Sell Big Poe"                                             => ("Item",                ADVANCEMENT, None,                                                      ["bottle" => f64::INFINITY]),
    "Magic Bean"                                               => ("Item",                ADVANCEMENT, GI_MAGIC_BEAN,                                             ["progressive" => 10_i32]),
    "Skull Mask"                                               => ("Item",                ADVANCEMENT, GI_MASK_SKULL,                                             ["trade" => true, "object" => 0x0136_i32]),
    "Spooky Mask"                                              => ("Item",                ADVANCEMENT, GI_MASK_SPOOKY,                                            ["trade" => true, "object" => 0x0135_i32]),
    "Chicken"                                                  => ("Item",                ADVANCEMENT, GI_CHICKEN,                                                ["trade" => true]),
    "Keaton Mask"                                              => ("Item",                ADVANCEMENT, GI_MASK_KEATON,                                            ["trade" => true, "object" => 0x0134_i32]),
    "Bunny Hood"                                               => ("Item",                ADVANCEMENT, GI_MASK_BUNNY_HOOD,                                        ["trade" => true, "object" => 0x0137_i32]),
    "Mask of Truth"                                            => ("Item",                ADVANCEMENT, GI_MASK_TRUTH,                                             ["trade" => true, "object" => 0x0138_i32]),
    "Pocket Egg"                                               => ("Item",                ADVANCEMENT, GI_POCKET_EGG,                                             ["trade" => true]),
    "Pocket Cucco"                                             => ("Item",                ADVANCEMENT, GI_POCKET_CUCCO,                                           ["trade" => true]),
    "Odd Mushroom"                                             => ("Item",                ADVANCEMENT, GI_ODD_MUSHROOM,                                           ["trade" => true]),
    "Odd Potion"                                               => ("Item",                ADVANCEMENT, GI_ODD_POTION,                                             ["trade" => true]),
    "Poachers Saw"                                             => ("Item",                ADVANCEMENT, GI_POACHERS_SAW,                                           ["trade" => true]),
    "Broken Sword"                                             => ("Item",                ADVANCEMENT, GI_BROKEN_GORONS_SWORD,                                    ["trade" => true]),
    "Prescription"                                             => ("Item",                ADVANCEMENT, GI_PRESCRIPTION,                                           ["trade" => true]),
    "Eyeball Frog"                                             => ("Item",                ADVANCEMENT, GI_EYEBALL_FROG,                                           ["trade" => true]),
    "Eyedrops"                                                 => ("Item",                ADVANCEMENT, GI_EYE_DROPS,                                              ["trade" => true]),
    "Claim Check"                                              => ("Item",                ADVANCEMENT, GI_CLAIM_CHECK,                                            ["trade" => true]),
    "Kokiri Sword"                                             => ("Item",                ADVANCEMENT, GI_SWORD_KOKIRI,                                           []),
    "Giants Knife"                                             => ("Item",                ADVANCEMENT, GI_SWORD_KNIFE,                                            []),
    "Deku Shield"                                              => ("Item",                NORMAL,      GI_SHIELD_DEKU,                                            ["market_price" => 40_i32]),
    "Hylian Shield"                                            => ("Item",                NORMAL,      GI_SHIELD_HYLIAN,                                          ["market_price" => 80_i32]),
    "Mirror Shield"                                            => ("Item",                ADVANCEMENT, GI_SHIELD_MIRROR,                                          []),
    "Goron Tunic"                                              => ("Item",                ADVANCEMENT, GI_TUNIC_GORON,                                            []),
    "Zora Tunic"                                               => ("Item",                ADVANCEMENT, GI_TUNIC_ZORA,                                             []),
    "Iron Boots"                                               => ("Item",                ADVANCEMENT, GI_BOOTS_IRON,                                             []),
    "Hover Boots"                                              => ("Item",                ADVANCEMENT, GI_BOOTS_HOVER,                                            []),
    "Stone of Agony"                                           => ("Item",                ADVANCEMENT, GI_STONE_OF_AGONY,                                         []),
    "Gerudo Membership Card"                                   => ("Item",                ADVANCEMENT, GI_GERUDOS_CARD,                                           []),
    "Heart Container"                                          => ("Item",                ADVANCEMENT, GI_HEART_CONTAINER,                                        ["alias" => ("Piece of Heart", 4), "progressive" => f64::INFINITY]),
    "Piece of Heart"                                           => ("Item",                ADVANCEMENT, GI_HEART_PIECE,                                            ["progressive" => f64::INFINITY]),
    "Piece of Heart (Out of Logic)"                            => ("Item",                NORMAL,      GI_HEART_PIECE,                                            []),
    "Boss Key"                                                 => ("BossKey",             ADVANCEMENT, GI_BOSS_KEY,                                               []),
    "Compass"                                                  => ("Compass",             NORMAL,      GI_COMPASS,                                                []),
    "Map"                                                      => ("Map",                 NORMAL,      GI_DUNGEON_MAP,                                            []),
    "Small Key"                                                => ("SmallKey",            ADVANCEMENT, GI_SMALL_KEY,                                              ["progressive" => f64::INFINITY]),
    "Weird Egg"                                                => ("Item",                ADVANCEMENT, GI_WEIRD_EGG,                                              ["trade" => true]),
    "Recovery Heart"                                           => ("Item",                NORMAL,      GI_RECOVERY_HEART,                                         ["junk" => 0_i32, "market_price" => 10_i32]),
    "Arrows (5)"                                               => ("Item",                NORMAL,      GI_ARROWS_5,                                               ["junk" => 8_i32]),
    "Arrows (10)"                                              => ("Item",                NORMAL,      GI_ARROWS_10,                                              ["junk" => 2_i32, "market_price" => 20_i32]),
    "Arrows (30)"                                              => ("Item",                NORMAL,      GI_ARROWS_30,                                              ["junk" => 0_i32, "market_price" => 60_i32]),
    "Rupee (1)"                                                => ("Item",                NORMAL,      GI_RUPEE_GREEN,                                            ["junk" => -1, "market_price" => 1_i32]),
    "Rupees (5)"                                               => ("Item",                NORMAL,      GI_RUPEE_BLUE,                                             ["junk" => 10_i32, "market_price" => 5_i32]),
    "Rupees (20)"                                              => ("Item",                NORMAL,      GI_RUPEE_RED,                                              ["junk" => 4_i32, "market_price" => 20_i32]),
    "Milk"                                                     => ("Item",                NORMAL,      GI_MILK,                                                   []),
    "Goron Mask"                                               => ("Item",                NORMAL,      GI_MASK_GORON,                                             ["trade" => true, "object" => 0x0150_i32]),
    "Zora Mask"                                                => ("Item",                NORMAL,      GI_MASK_ZORA,                                              ["trade" => true, "object" => 0x0151_i32]),
    "Gerudo Mask"                                              => ("Item",                NORMAL,      GI_MASK_GERUDO,                                            ["trade" => true, "object" => 0x0152_i32]),
    "Rupees (50)"                                              => ("Item",                NORMAL,      GI_RUPEE_PURPLE,                                           ["junk" => 1_i32, "market_price" => 50_i32]),
    "Rupees (200)"                                             => ("Item",                NORMAL,      GI_RUPEE_GOLD,                                             ["junk" => 0_i32, "market_price" => 200_i32]),
    "Biggoron Sword"                                           => ("Item",                ADVANCEMENT, GI_SWORD_BIGGORON,                                         []),
    "Fire Arrows"                                              => ("Item",                ADVANCEMENT, GI_ARROW_FIRE,                                             []),
    "Ice Arrows"                                               => ("Item",                ADVANCEMENT, GI_ARROW_ICE,                                              []),
    "Blue Fire Arrows"                                         => ("Item",                ADVANCEMENT, GI_ARROW_BLUE_FIRE,                                        []),
    "Light Arrows"                                             => ("Item",                ADVANCEMENT, GI_ARROW_LIGHT,                                            []),
    "Gold Skulltula Token"                                     => ("Token",               ADVANCEMENT, GI_SKULL_TOKEN,                                            ["progressive" => f64::INFINITY]),
    "Dins Fire"                                                => ("Item",                ADVANCEMENT, GI_DINS_FIRE,                                              []),
    "Farores Wind"                                             => ("Item",                ADVANCEMENT, GI_FARORES_WIND,                                           []),
    "Nayrus Love"                                              => ("Item",                ADVANCEMENT, GI_NAYRUS_LOVE,                                            []),
    "Deku Nuts (10)"                                           => ("Item",                NORMAL,      GI_DEKU_NUTS_10,                                           ["junk" => 0_i32, "market_price" => 30_i32]),
    "Bomb (1)"                                                 => ("Item",                NORMAL,      GI_BOMBS_1,                                                ["junk" => -1]),
    "Bombs (10)"                                               => ("Item",                NORMAL,      GI_BOMBS_10,                                               ["junk" => 2_i32, "market_price" => 50_i32]),
    "Bombs (20)"                                               => ("Item",                NORMAL,      GI_BOMBS_20,                                               ["junk" => 0_i32, "market_price" => 80_i32]),
    "Deku Seeds (30)"                                          => ("Item",                NORMAL,      GI_DEKU_SEEDS_30,                                          ["junk" => 5_i32, "market_price" => 30_i32]),
    "Bombchus (5)"                                             => ("Item",                ADVANCEMENT, GI_BOMBCHUS_5,                                             ["market_price" => 60_i32, "market_price_non_chu_drops_only" => true]),
    "Bombchus (20)"                                            => ("Item",                ADVANCEMENT, GI_BOMBCHUS_20,                                            ["market_price" => 180_i32, "market_price_non_chu_drops_only" => true]),
    "Small Key (Treasure Chest Game)"                          => ("TCGSmallKey",         ADVANCEMENT, GI_DOOR_KEY,                                               ["progressive" => f64::INFINITY]),
    "Rupee (Treasure Chest Game) (1)"                          => ("Item",                NORMAL,      GI_RUPEE_GREEN_LOSE,                                       ["market_price" => 1_i32]),
    "Rupees (Treasure Chest Game) (5)"                         => ("Item",                NORMAL,      GI_RUPEE_BLUE_LOSE,                                        ["market_price" => 5_i32]),
    "Rupees (Treasure Chest Game) (20)"                        => ("Item",                NORMAL,      GI_RUPEE_RED_LOSE,                                         ["market_price" => 20_i32]),
    "Rupees (Treasure Chest Game) (50)"                        => ("Item",                NORMAL,      GI_RUPEE_PURPLE_LOSE,                                      ["market_price" => 50_i32]),
    "Piece of Heart (Treasure Chest Game)"                     => ("Item",                ADVANCEMENT, GI_HEART_PIECE_WIN,                                        ["alias" => ("Piece of Heart", 1), "progressive" => f64::INFINITY]),
    "Ice Trap"                                                 => ("Item",                NORMAL,      GI_ICE_TRAP,                                               ["junk" => 0_i32]),
    "Progressive Hookshot"                                     => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_HOOKSHOT,                                   ["progressive" => 2_i32]),
    "Progressive Strength Upgrade"                             => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_STRENGTH,                                   ["progressive" => 3_i32]),
    "Bomb Bag"                                                 => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_BOMB_BAG,                                   []),
    "Bow"                                                      => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_BOW,                                        []),
    "Slingshot"                                                => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_SLINGSHOT,                                  []),
    "Deku Seed Bag"                                            => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_SLINGSHOT,                                  ["alias" => ("Slingshot", 1)]),
    "Progressive Wallet"                                       => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_WALLET,                                     ["progressive" => 3_i32]),
    "Progressive Scale"                                        => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_SCALE,                                      ["progressive" => 2_i32]),
    "Deku Nut Capacity"                                        => ("Item",                NORMAL,      GI_PROGRESSIVE_NUT_CAPACITY,                               []),
    "Deku Stick Capacity"                                      => ("Item",                NORMAL,      GI_PROGRESSIVE_STICK_CAPACITY,                             []),
    "Bombchus"                                                 => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_BOMBCHUS,                                   []),
    "Magic Meter"                                              => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_MAGIC_METER,                                []),
    "Ocarina"                                                  => ("Item",                ADVANCEMENT, GI_PROGRESSIVE_OCARINA,                                    ["progressive" => 2_i32]),
    "Bottle with Red Potion"                                   => ("Item",                ADVANCEMENT, GI_BOTTLE_WITH_RED_POTION,                                 ["bottle" => true, "shop_object" => 0x0F_i32]),
    "Bottle with Green Potion"                                 => ("Item",                ADVANCEMENT, GI_BOTTLE_WITH_GREEN_POTION,                               ["bottle" => true, "shop_object" => 0x0F_i32]),
    "Bottle with Blue Potion"                                  => ("Item",                ADVANCEMENT, GI_BOTTLE_WITH_BLUE_POTION,                                ["bottle" => true, "shop_object" => 0x0F_i32]),
    "Bottle with Fairy"                                        => ("Item",                ADVANCEMENT, GI_BOTTLE_WITH_FAIRY,                                      ["bottle" => true, "shop_object" => 0x0F_i32]),
    "Bottle with Fish"                                         => ("Item",                ADVANCEMENT, GI_BOTTLE_WITH_FISH,                                       ["bottle" => true, "shop_object" => 0x0F_i32]),
    "Bottle with Blue Fire"                                    => ("Item",                ADVANCEMENT, GI_BOTTLE_WITH_BLUE_FIRE,                                  ["bottle" => true, "shop_object" => 0x0F_i32]),
    "Bottle with Bugs"                                         => ("Item",                ADVANCEMENT, GI_BOTTLE_WITH_BUGS,                                       ["bottle" => true, "shop_object" => 0x0F_i32]),
    "Bottle with Big Poe"                                      => ("Item",                ADVANCEMENT, GI_BOTTLE_WITH_BIG_POE,                                    ["shop_object" => 0x0F_i32]),
    "Bottle with Poe"                                          => ("Item",                ADVANCEMENT, GI_BOTTLE_WITH_POE,                                        ["bottle" => true, "shop_object" => 0x0F_i32]),
    "Boss Key (Forest Temple)"                                 => ("BossKey",             ADVANCEMENT, GI_BOSS_KEY_FOREST_TEMPLE,                                 []),
    "Boss Key (Fire Temple)"                                   => ("BossKey",             ADVANCEMENT, GI_BOSS_KEY_FIRE_TEMPLE,                                   []),
    "Boss Key (Water Temple)"                                  => ("BossKey",             ADVANCEMENT, GI_BOSS_KEY_WATER_TEMPLE,                                  []),
    "Boss Key (Spirit Temple)"                                 => ("BossKey",             ADVANCEMENT, GI_BOSS_KEY_SPIRIT_TEMPLE,                                 []),
    "Boss Key (Shadow Temple)"                                 => ("BossKey",             ADVANCEMENT, GI_BOSS_KEY_SHADOW_TEMPLE,                                 []),
    "Boss Key (Ganons Castle)"                                 => ("GanonBossKey",        ADVANCEMENT, GI_BOSS_KEY_GANONS_CASTLE,                                 []),
    "Compass (Deku Tree)"                                      => ("Compass",             PRIORITY,    GI_COMPASS_DEKU_TREE,                                      []),
    "Compass (Dodongos Cavern)"                                => ("Compass",             PRIORITY,    GI_COMPASS_DODONGOS_CAVERN,                                []),
    "Compass (Jabu Jabus Belly)"                               => ("Compass",             PRIORITY,    GI_COMPASS_JABU_JABU,                                      []),
    "Compass (Forest Temple)"                                  => ("Compass",             PRIORITY,    GI_COMPASS_FOREST_TEMPLE,                                  []),
    "Compass (Fire Temple)"                                    => ("Compass",             PRIORITY,    GI_COMPASS_FIRE_TEMPLE,                                    []),
    "Compass (Water Temple)"                                   => ("Compass",             PRIORITY,    GI_COMPASS_WATER_TEMPLE,                                   []),
    "Compass (Spirit Temple)"                                  => ("Compass",             PRIORITY,    GI_COMPASS_SPIRIT_TEMPLE,                                  []),
    "Compass (Shadow Temple)"                                  => ("Compass",             PRIORITY,    GI_COMPASS_SHADOW_TEMPLE,                                  []),
    "Compass (Bottom of the Well)"                             => ("Compass",             PRIORITY,    GI_COMPASS_BOTTOM_OF_THE_WELL,                             []),
    "Compass (Ice Cavern)"                                     => ("Compass",             PRIORITY,    GI_COMPASS_ICE_CAVERN,                                     []),
    "Map (Deku Tree)"                                          => ("Map",                 PRIORITY,    GI_MAP_DEKU_TREE,                                          []),
    "Map (Dodongos Cavern)"                                    => ("Map",                 PRIORITY,    GI_MAP_DODONGOS_CAVERN,                                    []),
    "Map (Jabu Jabus Belly)"                                   => ("Map",                 PRIORITY,    GI_MAP_JABU_JABU,                                          []),
    "Map (Forest Temple)"                                      => ("Map",                 PRIORITY,    GI_MAP_FOREST_TEMPLE,                                      []),
    "Map (Fire Temple)"                                        => ("Map",                 PRIORITY,    GI_MAP_FIRE_TEMPLE,                                        []),
    "Map (Water Temple)"                                       => ("Map",                 PRIORITY,    GI_MAP_WATER_TEMPLE,                                       []),
    "Map (Spirit Temple)"                                      => ("Map",                 PRIORITY,    GI_MAP_SPIRIT_TEMPLE,                                      []),
    "Map (Shadow Temple)"                                      => ("Map",                 PRIORITY,    GI_MAP_SHADOW_TEMPLE,                                      []),
    "Map (Bottom of the Well)"                                 => ("Map",                 PRIORITY,    GI_MAP_BOTTOM_OF_THE_WELL,                                 []),
    "Map (Ice Cavern)"                                         => ("Map",                 PRIORITY,    GI_MAP_ICE_CAVERN,                                         []),
    "Small Key (Forest Temple)"                                => ("SmallKey",            ADVANCEMENT, GI_SMALL_KEY_FOREST_TEMPLE,                                ["progressive" => f64::INFINITY]),
    "Small Key (Fire Temple)"                                  => ("SmallKey",            ADVANCEMENT, GI_SMALL_KEY_FIRE_TEMPLE,                                  ["progressive" => f64::INFINITY]),
    "Small Key (Water Temple)"                                 => ("SmallKey",            ADVANCEMENT, GI_SMALL_KEY_WATER_TEMPLE,                                 ["progressive" => f64::INFINITY]),
    "Small Key (Spirit Temple)"                                => ("SmallKey",            ADVANCEMENT, GI_SMALL_KEY_SPIRIT_TEMPLE,                                ["progressive" => f64::INFINITY]),
    "Small Key (Shadow Temple)"                                => ("SmallKey",            ADVANCEMENT, GI_SMALL_KEY_SHADOW_TEMPLE,                                ["progressive" => f64::INFINITY]),
    "Small Key (Bottom of the Well)"                           => ("SmallKey",            ADVANCEMENT, GI_SMALL_KEY_BOTTOM_OF_THE_WELL,                           ["progressive" => f64::INFINITY]),
    "Small Key (Gerudo Training Ground)"                       => ("SmallKey",            ADVANCEMENT, GI_SMALL_KEY_GERUDO_TRAINING,                              ["progressive" => f64::INFINITY]),
    "Small Key (Thieves Hideout)"                              => ("HideoutSmallKey",     ADVANCEMENT, GI_SMALL_KEY_THIEVES_HIDEOUT,                              ["progressive" => f64::INFINITY]),
    "Small Key (Ganons Castle)"                                => ("SmallKey",            ADVANCEMENT, GI_SMALL_KEY_GANONS_CASTLE,                                ["progressive" => f64::INFINITY]),
    "Double Defense"                                           => ("Item",                NORMAL,      GI_DOUBLE_DEFENSE,                                         []),
    "Buy Magic Bean"                                           => ("Item",                ADVANCEMENT, GI_MAGIC_BEAN,                                             ["alias" => ("Magic Bean", 10), "progressive" => 10_i32]),
    "Magic Bean Pack"                                          => ("Item",                ADVANCEMENT, GI_MAGIC_BEAN_PACK,                                        ["alias" => ("Magic Bean", 10), "progressive" => 10_i32]),
    "Triforce Piece"                                           => ("Item",                ADVANCEMENT, GI_TRIFORCE_PIECE,                                         ["progressive" => f64::INFINITY]),
    "Zeldas Letter"                                            => ("Item",                ADVANCEMENT, GI_ZELDAS_LETTER,                                          ["trade" => true]),
    "Time Travel"                                              => ("Event",               ADVANCEMENT, None,                                                      []),
    "Scarecrow Song"                                           => ("Event",               ADVANCEMENT, None,                                                      []),
    "Triforce"                                                 => ("Event",               ADVANCEMENT, None,                                                      []),

    "Small Key Ring (Forest Temple)"                           => ("SmallKeyRing",        ADVANCEMENT, GI_SMALL_KEY_RING_FOREST_TEMPLE,                           ["alias" => ("Small Key (Forest Temple)", 10), "progressive" => f64::INFINITY]),
    "Small Key Ring (Fire Temple)"                             => ("SmallKeyRing",        ADVANCEMENT, GI_SMALL_KEY_RING_FIRE_TEMPLE,                             ["alias" => ("Small Key (Fire Temple)", 10), "progressive" => f64::INFINITY]),
    "Small Key Ring (Water Temple)"                            => ("SmallKeyRing",        ADVANCEMENT, GI_SMALL_KEY_RING_WATER_TEMPLE,                            ["alias" => ("Small Key (Water Temple)", 10), "progressive" => f64::INFINITY]),
    "Small Key Ring (Spirit Temple)"                           => ("SmallKeyRing",        ADVANCEMENT, GI_SMALL_KEY_RING_SPIRIT_TEMPLE,                           ["alias" => ("Small Key (Spirit Temple)", 10), "progressive" => f64::INFINITY]),
    "Small Key Ring (Shadow Temple)"                           => ("SmallKeyRing",        ADVANCEMENT, GI_SMALL_KEY_RING_SHADOW_TEMPLE,                           ["alias" => ("Small Key (Shadow Temple)", 10), "progressive" => f64::INFINITY]),
    "Small Key Ring (Bottom of the Well)"                      => ("SmallKeyRing",        ADVANCEMENT, GI_SMALL_KEY_RING_BOTTOM_OF_THE_WELL,                      ["alias" => ("Small Key (Bottom of the Well)", 10), "progressive" => f64::INFINITY]),
    "Small Key Ring (Gerudo Training Ground)"                  => ("SmallKeyRing",        ADVANCEMENT, GI_SMALL_KEY_RING_GERUDO_TRAINING,                         ["alias" => ("Small Key (Gerudo Training Ground)", 10), "progressive" => f64::INFINITY]),
    "Small Key Ring (Thieves Hideout)"                         => ("HideoutSmallKeyRing", ADVANCEMENT, GI_SMALL_KEY_RING_THIEVES_HIDEOUT,                         ["alias" => ("Small Key (Thieves Hideout)", 10), "progressive" => f64::INFINITY]),
    "Small Key Ring (Ganons Castle)"                           => ("SmallKeyRing",        ADVANCEMENT, GI_SMALL_KEY_RING_GANONS_CASTLE,                           ["alias" => ("Small Key (Ganons Castle)", 10), "progressive" => f64::INFINITY]),
    "Small Key Ring (Treasure Chest Game)"                     => ("TCGSmallKeyRing",     ADVANCEMENT, GI_SMALL_KEY_RING_TREASURE_CHEST_GAME,                     ["alias" => ("Small Key (Treasure Chest Game)", 10), "progressive" => f64::INFINITY]),

    "Silver Rupee (Dodongos Cavern Staircase)"                 => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_DODONGOS_CAVERN_STAIRCASE,                 ["progressive" => 5_i32]),
    "Silver Rupee (Ice Cavern Spinning Scythe)"                => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_ICE_CAVERN_SPINNING_SCYTHE,                ["progressive" => 5_i32]),
    "Silver Rupee (Ice Cavern Push Block)"                     => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_ICE_CAVERN_PUSH_BLOCK,                     ["progressive" => 5_i32]),
    "Silver Rupee (Bottom of the Well Basement)"               => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_BOTTOM_OF_THE_WELL_BASEMENT,               ["progressive" => 5_i32]),
    "Silver Rupee (Shadow Temple Scythe Shortcut)"             => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_SHADOW_TEMPLE_SCYTHE_SHORTCUT,             ["progressive" => 5_i32]),
    "Silver Rupee (Shadow Temple Invisible Blades)"            => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_SHADOW_TEMPLE_INVISIBLE_BLADES,            ["progressive" => 10_i32]),
    "Silver Rupee (Shadow Temple Huge Pit)"                    => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_SHADOW_TEMPLE_HUGE_PIT,                    ["progressive" => 5_i32]),
    "Silver Rupee (Shadow Temple Invisible Spikes)"            => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_SHADOW_TEMPLE_INVISIBLE_SPIKES,            ["progressive" => 10_i32]),
    "Silver Rupee (Gerudo Training Ground Slopes)"             => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_GERUDO_TRAINING_GROUND_SLOPES,             ["progressive" => 5_i32]),
    "Silver Rupee (Gerudo Training Ground Lava)"               => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_GERUDO_TRAINING_GROUND_LAVA,               ["progressive" => 6_i32]),
    "Silver Rupee (Gerudo Training Ground Water)"              => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_GERUDO_TRAINING_GROUND_WATER,              ["progressive" => 5_i32]),
    "Silver Rupee (Spirit Temple Child Early Torches)"         => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_SPIRIT_TEMPLE_CHILD_EARLY_TORCHES,         ["progressive" => 5_i32]),
    "Silver Rupee (Spirit Temple Adult Boulders)"              => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_SPIRIT_TEMPLE_ADULT_BOULDERS,              ["progressive" => 5_i32]),
    "Silver Rupee (Spirit Temple Lobby and Lower Adult)"       => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_SPIRIT_TEMPLE_LOBBY_AND_LOWER_ADULT,       ["progressive" => 5_i32]),
    "Silver Rupee (Spirit Temple Sun Block)"                   => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_SPIRIT_TEMPLE_SUN_BLOCK,                   ["progressive" => 5_i32]),
    "Silver Rupee (Spirit Temple Adult Climb)"                 => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_SPIRIT_TEMPLE_ADULT_CLIMB,                 ["progressive" => 5_i32]),
    "Silver Rupee (Ganons Castle Spirit Trial)"                => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_GANONS_CASTLE_SPIRIT_TRIAL,                ["progressive" => 5_i32]),
    "Silver Rupee (Ganons Castle Light Trial)"                 => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_GANONS_CASTLE_LIGHT_TRIAL,                 ["progressive" => 5_i32]),
    "Silver Rupee (Ganons Castle Fire Trial)"                  => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_GANONS_CASTLE_FIRE_TRIAL,                  ["progressive" => 5_i32]),
    "Silver Rupee (Ganons Castle Shadow Trial)"                => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_GANONS_CASTLE_SHADOW_TRIAL,                ["progressive" => 5_i32]),
    "Silver Rupee (Ganons Castle Water Trial)"                 => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_GANONS_CASTLE_WATER_TRIAL,                 ["progressive" => 5_i32]),
    "Silver Rupee (Ganons Castle Forest Trial)"                => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_GANONS_CASTLE_FOREST_TRIAL,                ["progressive" => 5_i32]),

    "Silver Rupee Pouch (Dodongos Cavern Staircase)"           => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_DODONGOS_CAVERN_STAIRCASE,           ["alias" => ("Silver Rupee (Dodongos Cavern Staircase)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Ice Cavern Spinning Scythe)"          => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_ICE_CAVERN_SPINNING_SCYTHE,          ["alias" => ("Silver Rupee (Ice Cavern Spinning Scythe)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Ice Cavern Push Block)"               => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_ICE_CAVERN_PUSH_BLOCK,               ["alias" => ("Silver Rupee (Ice Cavern Push Block)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Bottom of the Well Basement)"         => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_BOTTOM_OF_THE_WELL_BASEMENT,         ["alias" => ("Silver Rupee (Bottom of the Well Basement)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Shadow Temple Scythe Shortcut)"       => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_SHADOW_TEMPLE_SCYTHE_SHORTCUT,       ["alias" => ("Silver Rupee (Shadow Temple Scythe Shortcut)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Shadow Temple Invisible Blades)"      => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_SHADOW_TEMPLE_INVISIBLE_BLADES,      ["alias" => ("Silver Rupee (Shadow Temple Invisible Blades)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Shadow Temple Huge Pit)"              => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_SHADOW_TEMPLE_HUGE_PIT,              ["alias" => ("Silver Rupee (Shadow Temple Huge Pit)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Shadow Temple Invisible Spikes)"      => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_SHADOW_TEMPLE_INVISIBLE_SPIKES,      ["alias" => ("Silver Rupee (Shadow Temple Invisible Spikes)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Gerudo Training Ground Slopes)"       => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_GERUDO_TRAINING_GROUND_SLOPES,       ["alias" => ("Silver Rupee (Gerudo Training Ground Slopes)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Gerudo Training Ground Lava)"         => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_GERUDO_TRAINING_GROUND_LAVA,         ["alias" => ("Silver Rupee (Gerudo Training Ground Lava)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Gerudo Training Ground Water)"        => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_GERUDO_TRAINING_GROUND_WATER,        ["alias" => ("Silver Rupee (Gerudo Training Ground Water)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Spirit Temple Child Early Torches)"   => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_CHILD_EARLY_TORCHES,   ["alias" => ("Silver Rupee (Spirit Temple Child Early Torches)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Spirit Temple Adult Boulders)"        => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_ADULT_BOULDERS,        ["alias" => ("Silver Rupee (Spirit Temple Adult Boulders)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Spirit Temple Lobby and Lower Adult)" => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_LOBBY_AND_LOWER_ADULT, ["alias" => ("Silver Rupee (Spirit Temple Lobby and Lower Adult)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Spirit Temple Sun Block)"             => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_SUN_BLOCK,             ["alias" => ("Silver Rupee (Spirit Temple Sun Block)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Spirit Temple Adult Climb)"           => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_SPIRIT_TEMPLE_ADULT_CLIMB,           ["alias" => ("Silver Rupee (Spirit Temple Adult Climb)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Ganons Castle Spirit Trial)"          => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_SPIRIT_TRIAL,          ["alias" => ("Silver Rupee (Ganons Castle Spirit Trial)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Ganons Castle Light Trial)"           => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_LIGHT_TRIAL,           ["alias" => ("Silver Rupee (Ganons Castle Light Trial)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Ganons Castle Fire Trial)"            => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_FIRE_TRIAL,            ["alias" => ("Silver Rupee (Ganons Castle Fire Trial)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Ganons Castle Shadow Trial)"          => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_SHADOW_TRIAL,          ["alias" => ("Silver Rupee (Ganons Castle Shadow Trial)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Ganons Castle Water Trial)"           => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_WATER_TRIAL,           ["alias" => ("Silver Rupee (Ganons Castle Water Trial)", 10), "progressive" => 1_i32]),
    "Silver Rupee Pouch (Ganons Castle Forest Trial)"          => ("SilverRupee",         ADVANCEMENT, GI_SILVER_RUPEE_POUCH_GANONS_CASTLE_FOREST_TRIAL,          ["alias" => ("Silver Rupee (Ganons Castle Forest Trial)", 10), "progressive" => 1_i32]),

    "Ocarina A Button"                                         => ("Item",                ADVANCEMENT, GI_OCARINA_BUTTON_A,                                       ["ocarina_button" => true]),
    "Ocarina C up Button"                                      => ("Item",                ADVANCEMENT, GI_OCARINA_BUTTON_C_UP,                                    ["ocarina_button" => true]),
    "Ocarina C down Button"                                    => ("Item",                ADVANCEMENT, GI_OCARINA_BUTTON_C_DOWN,                                  ["ocarina_button" => true]),
    "Ocarina C left Button"                                    => ("Item",                ADVANCEMENT, GI_OCARINA_BUTTON_C_LEFT,                                  ["ocarina_button" => true]),
    "Ocarina C right Button"                                   => ("Item",                ADVANCEMENT, GI_OCARINA_BUTTON_C_RIGHT,                                 ["ocarina_button" => true]),
    "Fairy Drop"                                               => ("Item",                NORMAL,      GI_FAIRY,                                                  ["market_price" => 50_i32]),
    "Nothing"                                                  => ("Item",                NORMAL,      GI_NOTHING,                                                []),

    "Easter Egg (Pink)"                                        => ("Item",                ADVANCEMENT, GI_EASTER_EGG_PINK,                                        ["alias" => ("Triforce Piece", 1), "progressive" => f64::INFINITY]),
    "Easter Egg (Orange)"                                      => ("Item",                ADVANCEMENT, GI_EASTER_EGG_ORANGE,                                      ["alias" => ("Triforce Piece", 1), "progressive" => f64::INFINITY]),
    "Easter Egg (Green)"                                       => ("Item",                ADVANCEMENT, GI_EASTER_EGG_GREEN,                                       ["alias" => ("Triforce Piece", 1), "progressive" => f64::INFINITY]),
    "Easter Egg (Blue)"                                        => ("Item",                ADVANCEMENT, GI_EASTER_EGG_BLUE,                                        ["alias" => ("Triforce Piece", 1), "progressive" => f64::INFINITY]),

    "Triforce of Power"                                        => ("Item",                ADVANCEMENT, GI_TRIFORCE_OF_POWER,                                      ["alias" => ("Triforce Piece", 1), "progressive" => f64::INFINITY]),
    "Triforce of Wisdom"                                       => ("Item",                ADVANCEMENT, GI_TRIFORCE_OF_WISDOM,                                     ["alias" => ("Triforce Piece", 1), "progressive" => f64::INFINITY]),
    "Triforce of Courage"                                      => ("Item",                ADVANCEMENT, GI_TRIFORCE_OF_COURAGE,                                    ["alias" => ("Triforce Piece", 1), "progressive" => f64::INFINITY]),

    // Event items otherwise generated by generic event logic
    // can be defined here to enforce their appearance in playthroughs.
    "Deku Tree Clear"                                          => ("Event",               ADVANCEMENT, None,                                                      []),
    "Water Temple Clear"                                       => ("Event",               ADVANCEMENT, None,                                                      []),
    "Forest Trial Clear"                                       => ("Event",               ADVANCEMENT, None,                                                      []),
    "Fire Trial Clear"                                         => ("Event",               ADVANCEMENT, None,                                                      []),
    "Water Trial Clear"                                        => ("Event",               ADVANCEMENT, None,                                                      []),
    "Shadow Trial Clear"                                       => ("Event",               ADVANCEMENT, None,                                                      []),
    "Spirit Trial Clear"                                       => ("Event",               ADVANCEMENT, None,                                                      []),
    "Light Trial Clear"                                        => ("Event",               ADVANCEMENT, None,                                                      []),
    "Epona"                                                    => ("Event",               ADVANCEMENT, None,                                                      []),

    "Deku Stick Drop"                                          => ("Drop",                ADVANCEMENT, None,                                                      []),
    "Deku Nut Drop"                                            => ("Drop",                ADVANCEMENT, None,                                                      []),
    "Blue Fire"                                                => ("Drop",                ADVANCEMENT, None,                                                      []),
    "Fairy"                                                    => ("Drop",                ADVANCEMENT, None,                                                      []),
    "Fish"                                                     => ("Drop",                ADVANCEMENT, None,                                                      []),
    "Bugs"                                                     => ("Drop",                ADVANCEMENT, None,                                                      []),
    "Big Poe"                                                  => ("Drop",                ADVANCEMENT, None,                                                      []),
    "Bombchu Drop"                                             => ("Drop",                ADVANCEMENT, None,                                                      []),
    "Deku Shield Drop"                                         => ("Drop",                ADVANCEMENT, None,                                                      []),

    // Consumable refills defined mostly to placate "starting with" options
    "Arrows"                                                   => ("Refill",              NORMAL,      None,                                                      []),
    "Bombs"                                                    => ("Refill",              NORMAL,      None,                                                      []),
    "Deku Seeds"                                               => ("Refill",              NORMAL,      None,                                                      []),
    "Deku Sticks"                                              => ("Refill",              NORMAL,      None,                                                      []),
    "Deku Nuts"                                                => ("Refill",              NORMAL,      None,                                                      []),
    "Rupees"                                                   => ("Refill",              NORMAL,      None,                                                      []),

    "Minuet of Forest"                                         => ("Song",                ADVANCEMENT, GI_MINUET_OF_FOREST,                                       ["text_id" => 0x73_i32, "song_id" => 0x02_i32, "item_id" => 0x5A_i32]),
    "Bolero of Fire"                                           => ("Song",                ADVANCEMENT, GI_BOLERO_OF_FIRE,                                         ["text_id" => 0x74_i32, "song_id" => 0x03_i32, "item_id" => 0x5B_i32]),
    "Serenade of Water"                                        => ("Song",                ADVANCEMENT, GI_SERENADE_OF_WATER,                                      ["text_id" => 0x75_i32, "song_id" => 0x04_i32, "item_id" => 0x5C_i32]),
    "Requiem of Spirit"                                        => ("Song",                ADVANCEMENT, GI_REQUIEM_OF_SPIRIT,                                      ["text_id" => 0x76_i32, "song_id" => 0x05_i32, "item_id" => 0x5D_i32]),
    "Nocturne of Shadow"                                       => ("Song",                ADVANCEMENT, GI_NOCTURNE_OF_SHADOW,                                     ["text_id" => 0x77_i32, "song_id" => 0x06_i32, "item_id" => 0x5E_i32]),
    "Prelude of Light"                                         => ("Song",                ADVANCEMENT, GI_PRELUDE_OF_LIGHT,                                       ["text_id" => 0x78_i32, "song_id" => 0x07_i32, "item_id" => 0x5F_i32]),
    "Zeldas Lullaby"                                           => ("Song",                ADVANCEMENT, GI_ZELDAS_LULLABY,                                         ["text_id" => 0xD4_i32, "song_id" => 0x0A_i32, "item_id" => 0x60_i32]),
    "Eponas Song"                                              => ("Song",                ADVANCEMENT, GI_EPONAS_SONG,                                            ["text_id" => 0xD2_i32, "song_id" => 0x09_i32, "item_id" => 0x61_i32]),
    "Sarias Song"                                              => ("Song",                ADVANCEMENT, GI_SARIAS_SONG,                                            ["text_id" => 0xD1_i32, "song_id" => 0x08_i32, "item_id" => 0x62_i32]),
    "Suns Song"                                                => ("Song",                ADVANCEMENT, GI_SUNS_SONG,                                              ["text_id" => 0xD3_i32, "song_id" => 0x0B_i32, "item_id" => 0x63_i32]),
    "Song of Time"                                             => ("Song",                ADVANCEMENT, GI_SONG_OF_TIME,                                           ["text_id" => 0xD5_i32, "song_id" => 0x0C_i32, "item_id" => 0x64_i32]),
    "Song of Storms"                                           => ("Song",                ADVANCEMENT, GI_SONG_OF_STORMS,                                         ["text_id" => 0xD6_i32, "song_id" => 0x0D_i32, "item_id" => 0x65_i32]),

    "Buy Deku Nut (5)"                                         => ("Shop",                ADVANCEMENT, 0x00,                                                      ["object" => 0x00BB_i32, "price" => 15_i32]),
    "Buy Arrows (30)"                                          => ("Shop",                PRIORITY,    0x01,                                                      ["object" => 0x00D8_i32, "price" => 60_i32]),
    "Buy Arrows (50)"                                          => ("Shop",                PRIORITY,    0x02,                                                      ["object" => 0x00D8_i32, "price" => 90_i32]),
    "Buy Bombs (5) for 25 Rupees"                              => ("Shop",                PRIORITY,    0x03,                                                      ["object" => 0x00CE_i32, "price" => 25_i32]),
    "Buy Deku Nut (10)"                                        => ("Shop",                ADVANCEMENT, 0x04,                                                      ["object" => 0x00BB_i32, "price" => 30_i32]),
    "Buy Deku Stick (1)"                                       => ("Shop",                ADVANCEMENT, 0x05,                                                      ["object" => 0x00C7_i32, "price" => 10_i32]),
    "Buy Bombs (10)"                                           => ("Shop",                PRIORITY,    0x06,                                                      ["object" => 0x00CE_i32, "price" => 50_i32]),
    "Buy Fish"                                                 => ("Shop",                ADVANCEMENT, 0x07,                                                      ["object" => 0x00F4_i32, "price" => 200_i32]),
    "Buy Red Potion for 30 Rupees"                             => ("Shop",                PRIORITY,    0x08,                                                      ["object" => 0x00EB_i32, "price" => 30_i32]),
    "Buy Green Potion"                                         => ("Shop",                PRIORITY,    0x09,                                                      ["object" => 0x00EB_i32, "price" => 30_i32]),
    "Buy Blue Potion"                                          => ("Shop",                PRIORITY,    0x0A,                                                      ["object" => 0x00EB_i32, "price" => 100_i32]),
    "Buy Hylian Shield"                                        => ("Shop",                ADVANCEMENT, 0x0C,                                                      ["object" => 0x00DC_i32, "price" => 80_i32]),
    "Buy Deku Shield"                                          => ("Shop",                ADVANCEMENT, 0x0D,                                                      ["object" => 0x00CB_i32, "price" => 40_i32]),
    "Buy Goron Tunic"                                          => ("Shop",                ADVANCEMENT, 0x0E,                                                      ["object" => 0x00F2_i32, "price" => 200_i32]),
    "Buy Zora Tunic"                                           => ("Shop",                ADVANCEMENT, 0x0F,                                                      ["object" => 0x00F2_i32, "price" => 300_i32]),
    "Buy Heart"                                                => ("Shop",                PRIORITY,    0x10,                                                      ["object" => 0x00B7_i32, "price" => 10_i32]),
    "Buy Bombchu (10)"                                         => ("Shop",                ADVANCEMENT, 0x15,                                                      ["object" => 0x00D9_i32, "price" => 99_i32]),
    "Buy Bombchu (20)"                                         => ("Shop",                ADVANCEMENT, 0x16,                                                      ["object" => 0x00D9_i32, "price" => 180_i32]),
    "Buy Bombchu (5)"                                          => ("Shop",                ADVANCEMENT, 0x18,                                                      ["object" => 0x00D9_i32, "price" => 60_i32]),
    "Buy Deku Seeds (30)"                                      => ("Shop",                PRIORITY,    0x1D,                                                      ["object" => 0x0119_i32, "price" => 30_i32]),
    "Sold Out"                                                 => ("Shop",                PRIORITY,    0x26,                                                      ["object" => 0x0148_i32]),
    "Buy Blue Fire"                                            => ("Shop",                ADVANCEMENT, 0x27,                                                      ["object" => 0x0173_i32, "price" => 300_i32]),
    "Buy Bottle Bug"                                           => ("Shop",                ADVANCEMENT, 0x28,                                                      ["object" => 0x0174_i32, "price" => 50_i32]),
    "Buy Poe"                                                  => ("Shop",                PRIORITY,    0x2A,                                                      ["object" => 0x0176_i32, "price" => 30_i32]),
    "Buy Fairy's Spirit"                                       => ("Shop",                ADVANCEMENT, 0x2B,                                                      ["object" => 0x0177_i32, "price" => 50_i32]),
    "Buy Arrows (10)"                                          => ("Shop",                PRIORITY,    0x2C,                                                      ["object" => 0x00D8_i32, "price" => 20_i32]),
    "Buy Bombs (20)"                                           => ("Shop",                PRIORITY,    0x2D,                                                      ["object" => 0x00CE_i32, "price" => 80_i32]),
    "Buy Bombs (30)"                                           => ("Shop",                PRIORITY,    0x2E,                                                      ["object" => 0x00CE_i32, "price" => 120_i32]),
    "Buy Bombs (5) for 35 Rupees"                              => ("Shop",                PRIORITY,    0x2F,                                                      ["object" => 0x00CE_i32, "price" => 35_i32]),
    "Buy Red Potion for 40 Rupees"                             => ("Shop",                PRIORITY,    0x30,                                                      ["object" => 0x00EB_i32, "price" => 40_i32]),
    "Buy Red Potion for 50 Rupees"                             => ("Shop",                PRIORITY,    0x31,                                                      ["object" => 0x00EB_i32, "price" => 50_i32]),

    "Kokiri Emerald"                                           => ("DungeonReward",       ADVANCEMENT, GI_KOKIRI_EMERALD,                                         ["stone" => true, "item_id" => 0x6C_i32]),
    "Goron Ruby"                                               => ("DungeonReward",       ADVANCEMENT, GI_GORON_RUBY,                                             ["stone" => true, "item_id" => 0x6D_i32]),
    "Zora Sapphire"                                            => ("DungeonReward",       ADVANCEMENT, GI_ZORA_SAPPHIRE,                                          ["stone" => true, "item_id" => 0x6E_i32]),
    "Light Medallion"                                          => ("DungeonReward",       ADVANCEMENT, GI_LIGHT_MEDALLION,                                        ["medallion" => true, "item_id" => 0x6B_i32]),
    "Forest Medallion"                                         => ("DungeonReward",       ADVANCEMENT, GI_FOREST_MEDALLION,                                       ["medallion" => true, "item_id" => 0x66_i32]),
    "Fire Medallion"                                           => ("DungeonReward",       ADVANCEMENT, GI_FIRE_MEDALLION,                                         ["medallion" => true, "item_id" => 0x67_i32]),
    "Water Medallion"                                          => ("DungeonReward",       ADVANCEMENT, GI_WATER_MEDALLION,                                        ["medallion" => true, "item_id" => 0x68_i32]),
    "Shadow Medallion"                                         => ("DungeonReward",       ADVANCEMENT, GI_SHADOW_MEDALLION,                                       ["medallion" => true, "item_id" => 0x6A_i32]),
    "Spirit Medallion"                                         => ("DungeonReward",       ADVANCEMENT, GI_SPIRIT_MEDALLION,                                       ["medallion" => true, "item_id" => 0x69_i32]),
}

pub(crate) fn module(py: Python<'_>) -> PyResult<Bound<'_, PyModule>> {
    let m = PyModule::new(py, "item_list")?;
    let mod_get_item_id = PyModule::new(py, "GetItemId")?;
    for (name, value) in get_item_id() {
        mod_get_item_id.add(name, value)?;
    }
    m.add_submodule(&mod_get_item_id)?;
    m.add("item_table", item_table(py)?)?;
    Ok(m)
}
